clean:
	@rm -rf **/.py && rm -rf **/__pycache__

install-dev:
	@pip install -r app/requirements/development.txt

test:
	@python app/manage.py test

provision:
	@ansible 

runserver:
	 @python app/manage.py runserver

